name: MaceStructure
version: '${version}'
main: net.saturn.maceStructure.StructurePlugin
api-version: '1.21'
authors: [ PumpkinDev ]

commands:
  findmace:
    description: Locate the mace structure
    usage: /findmace
    permission: macestructure.findmace
    permission-message: You don't have permission to use this command.
  mace:
    description: Mace utilities
    usage: /mace cooldown <seconds>
    permission: macestructure.mace
    permission-message: You don't have permission to use this command.

permissions:
  macestructure.findmace:
    description: Allows use of /findmace
    default: op
  macestructure.mace:
    description: Allows use of /mace
    default: op
