name: MaceStructure
version: '${version}'
main: net.saturn.maceStructure.StructurePlugin
api-version: '1.21'
authors: [ PumpkinDev ]

commands:
  findmace:
    description: Locate the mace structure
    usage: /findmace
  mace:
    description: Mace utilities
    usage: /mace cooldown <seconds>
