name: MaceStructure
version: '${version}'
main: net.saturn.maceStructure.MaceStructure
api-version: '1.21'
authors: [ PumpkinDev ]

permissions:
  macestructure.tp:
    description: Teleport to the mace structure
    default: op
  macestructure.gen:
    description: Manually trigger structure generation
    default: op